image: node:latest

pages:
  cache:
    paths:
      - node_modules/

  script:
    - npm i firebase-tools -g
    - npm run build
    - npm run generate
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - 1.2
